version: "3.8"

services:
  db:
    restart: always
    image: "postgres:latest"
    environment: 
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=QN
    ports:
      - "5432:5432"
    
  cache:
    image: "redis:latest"
    restart: always
  
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # - /app/node_modules
      - ./client:/app
    ports: 
      - "3000:3000"


  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=QN
      - DB_CACHE_HOST=cache
      - DB_CACHE_PORT=6379
      - NODE_ENV=dev
      
    ports: 
        - "5000:5000"
  
  apitest:
    stdin_open: true
    tty: true
    command: ["npm","run","test:watch"]
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=QN
      - DB_CACHE_HOST=cache
      - DB_CACHE_PORT=6379
      - NODE_ENV=test



